services:
  sql-server-db:
    container_name: sql-server-db
    image: mysql
    ports:
      - 8891:3306
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "12345678"
      ACCEPT_EULA: "Y"
    volumes:
      - /tmp/orens_data:/data
  
  my-app:
    container_name: vacation_app
    build: 
      context: .
      # target: production
      dockerfile: Dockerfile
    ports:
      - 8080:3001
    restart: always
    depends_on:
      - sql-server-db

volumes:
  data: {}
