services:
  sql-server-db:
    container_name: sql-server-db
    image: mysql
    command: --init-file /data/application/init.sql
    volumes:
      - ./backend/Utils/init.sql:/data/application/init.sql
    restart: always
    environment:
      MYSQL_ROOT_USERNAME: "root"
      MYSQL_ROOT_PASSWORD: "12345678"
      MYSQL_ROOT_DARABASE: "vacation"
      ACCEPT_EULA: "Y"
  
  my-app:
    container_name: vacation_app
    build: 
      context: .
      # target: production
      dockerfile: Dockerfile
    ports:
      - 8080:3001
    restart: always
    depends_on:
      - sql-server-db

volumes:
  data: {}